/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;

/**
 *
 * @author TURKEYTITAN
 */
public class PruebasLogin extends javax.swing.JFrame {

    /**
     * Creates new form PruebasLogin
     */
    public PruebasLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        textoNombres = new javax.swing.JTextField();
        Apellidos = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        JAtras = new javax.swing.JPanel();
        atras = new javax.swing.JLabel();
        JGuardar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        umedic = new javax.swing.JLabel();
        logoUmedic = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textoCorreo = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        Nombres = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        correoElctronico = new javax.swing.JLabel();
        textousuario = new javax.swing.JTextField();
        textoApellidos = new javax.swing.JTextField();
        textoContraseña = new javax.swing.JTextField();
        textoDireccion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkGradientFocus(100);
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setLayout(null);

        textoNombres.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textoNombres.setForeground(new java.awt.Color(255, 255, 255));
        textoNombres.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        textoNombres.setCaretColor(new java.awt.Color(255, 255, 255));
        textoNombres.setOpaque(false);
        textoNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombresActionPerformed(evt);
            }
        });
        kGradientPanel1.add(textoNombres);
        textoNombres.setBounds(150, 140, 290, 30);

        Apellidos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Apellidos.setForeground(new java.awt.Color(255, 255, 255));
        Apellidos.setText("Apellidos");
        kGradientPanel1.add(Apellidos);
        Apellidos.setBounds(560, 120, 90, 20);

        direccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        direccion.setForeground(new java.awt.Color(255, 255, 255));
        direccion.setText("Dirección");
        kGradientPanel1.add(direccion);
        direccion.setBounds(560, 290, 140, 20);

        JAtras.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        JAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JAtras.setOpaque(false);
        JAtras.setLayout(null);

        atras.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atras.setForeground(new java.awt.Color(255, 255, 255));
        atras.setText("Atrás");
        JAtras.add(atras);
        atras.setBounds(40, 0, 40, 20);

        kGradientPanel1.add(JAtras);
        JAtras.setBounds(640, 450, 120, 30);

        JGuardar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        JGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JGuardar.setOpaque(false);
        JGuardar.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Guardar");
        JGuardar.add(jLabel3);
        jLabel3.setBounds(30, 0, 60, 20);

        kGradientPanel1.add(JGuardar);
        JGuardar.setBounds(810, 450, 120, 30);

        umedic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        umedic.setForeground(new java.awt.Color(255, 255, 255));
        umedic.setText("Umedic");
        kGradientPanel1.add(umedic);
        umedic.setBounds(80, 20, 70, 40);

        logoUmedic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Corazon40.png"))); // NOI18N
        kGradientPanel1.add(logoUmedic);
        logoUmedic.setBounds(20, 20, 50, 50);

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CloseWhite.png"))); // NOI18N
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel1.add(Close);
        Close.setBounds(950, 20, 30, 20);

        Minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menos.png"))); // NOI18N
        Minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kGradientPanel1.add(Minimize);
        Minimize.setBounds(900, 20, 30, 30);
        kGradientPanel1.add(jLabel4);
        jLabel4.setBounds(880, 30, 40, 30);

        textoCorreo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textoCorreo.setForeground(new java.awt.Color(255, 255, 255));
        textoCorreo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        textoCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        textoCorreo.setOpaque(false);
        textoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCorreoActionPerformed(evt);
            }
        });
        kGradientPanel1.add(textoCorreo);
        textoCorreo.setBounds(150, 310, 290, 30);

        contraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setText("Contraseña");
        kGradientPanel1.add(contraseña);
        contraseña.setBounds(560, 200, 80, 20);

        Nombres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Nombres.setForeground(new java.awt.Color(255, 255, 255));
        Nombres.setText("Nombres");
        kGradientPanel1.add(Nombres);
        Nombres.setBounds(150, 120, 120, 20);

        usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setText("Usuario");
        kGradientPanel1.add(usuario);
        usuario.setBounds(150, 200, 80, 20);

        correoElctronico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        correoElctronico.setForeground(new java.awt.Color(255, 255, 255));
        correoElctronico.setText("Correo Electrónico");
        kGradientPanel1.add(correoElctronico);
        correoElctronico.setBounds(150, 290, 140, 20);

        textousuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textousuario.setForeground(new java.awt.Color(255, 255, 255));
        textousuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        textousuario.setCaretColor(new java.awt.Color(255, 255, 255));
        textousuario.setOpaque(false);
        textousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textousuarioActionPerformed(evt);
            }
        });
        kGradientPanel1.add(textousuario);
        textousuario.setBounds(150, 220, 290, 30);

        textoApellidos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textoApellidos.setForeground(new java.awt.Color(255, 255, 255));
        textoApellidos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        textoApellidos.setCaretColor(new java.awt.Color(255, 255, 255));
        textoApellidos.setOpaque(false);
        textoApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoApellidosActionPerformed(evt);
            }
        });
        kGradientPanel1.add(textoApellidos);
        textoApellidos.setBounds(560, 140, 290, 30);

        textoContraseña.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        textoContraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        textoContraseña.setCaretColor(new java.awt.Color(255, 255, 255));
        textoContraseña.setOpaque(false);
        textoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoContraseñaActionPerformed(evt);
            }
        });
        kGradientPanel1.add(textoContraseña);
        textoContraseña.setBounds(560, 220, 290, 30);

        textoDireccion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        textoDireccion.setForeground(new java.awt.Color(255, 255, 255));
        textoDireccion.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        textoDireccion.setCaretColor(new java.awt.Color(255, 255, 255));
        textoDireccion.setOpaque(false);
        textoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoDireccionActionPerformed(evt);
            }
        });
        kGradientPanel1.add(textoDireccion);
        textoDireccion.setBounds(560, 310, 290, 30);

        getContentPane().add(kGradientPanel1);
        kGradientPanel1.setBounds(0, 0, 1001, 623);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombresActionPerformed

    private void textoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCorreoActionPerformed

    private void textousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textousuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textousuarioActionPerformed

    private void textoApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoApellidosActionPerformed

    private void textoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoContraseñaActionPerformed

    private void textoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoDireccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebasLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebasLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebasLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebasLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebasLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.JLabel Close;
    private javax.swing.JPanel JAtras;
    private javax.swing.JPanel JGuardar;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel Nombres;
    private javax.swing.JLabel atras;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel correoElctronico;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel logoUmedic;
    private javax.swing.JTextField textoApellidos;
    private javax.swing.JTextField textoContraseña;
    private javax.swing.JTextField textoCorreo;
    private javax.swing.JTextField textoDireccion;
    private javax.swing.JTextField textoNombres;
    private javax.swing.JTextField textousuario;
    private javax.swing.JLabel umedic;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
