/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebas;

/**
 *
 * @author Kilmainham
 */
public class Pruebas1 extends javax.swing.JFrame {

    /**
     * Creates new form Pruebas1
     */
    public Pruebas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Izquierda = new javax.swing.JPanel();
        JCategoria = new javax.swing.JPanel();
        categoriasl = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        JCarrito = new javax.swing.JPanel();
        comprasl = new javax.swing.JLabel();
        buy = new javax.swing.JLabel();
        JAyuda = new javax.swing.JPanel();
        ayudal = new javax.swing.JLabel();
        safe = new javax.swing.JLabel();
        JAcerca = new javax.swing.JPanel();
        acercaL = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        JHeader = new javax.swing.JPanel();
        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        titleHeader = new javax.swing.JLabel();
        iconHeader = new javax.swing.JLabel();
        JBody = new javax.swing.JPanel();
        JClig = new javax.swing.JPanel();
        Glig = new javax.swing.JLabel();
        JTricovi = new javax.swing.JPanel();
        Tricovit = new javax.swing.JLabel();
        JDolexNi = new javax.swing.JPanel();
        Dolexni = new javax.swing.JLabel();
        JDolfenox = new javax.swing.JPanel();
        Dolfenox = new javax.swing.JLabel();
        JDolex = new javax.swing.JPanel();
        Dolex = new javax.swing.JLabel();
        JVoltaren = new javax.swing.JPanel();
        voltaren = new javax.swing.JLabel();
        priceDolfenox = new javax.swing.JLabel();
        priceGli = new javax.swing.JLabel();
        PriceDolex = new javax.swing.JLabel();
        priceTricovi = new javax.swing.JLabel();
        PriceVoltaren = new javax.swing.JLabel();
        priceDolexNi = new javax.swing.JLabel();
        buttonDolfenox = new javax.swing.JButton();
        buttonGlic = new javax.swing.JButton();
        butonDolex = new javax.swing.JButton();
        buttonTricovit = new javax.swing.JButton();
        buttonVoltaren = new javax.swing.JButton();
        buttonDolexNi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        Izquierda.setBackground(new java.awt.Color(54, 33, 89));
        Izquierda.setPreferredSize(new java.awt.Dimension(270, 610));
        Izquierda.setLayout(null);

        JCategoria.setBackground(new java.awt.Color(85, 65, 118));
        JCategoria.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 2, 0));
        JCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JCategoria.setPreferredSize(new java.awt.Dimension(270, 40));
        JCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JCategoriaMouseEntered(evt);
            }
        });
        JCategoria.setLayout(null);

        categoriasl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        categoriasl.setForeground(new java.awt.Color(204, 204, 204));
        categoriasl.setText("Categorias");
        JCategoria.add(categoriasl);
        categoriasl.setBounds(90, 10, 150, 20);

        category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Category30.png"))); // NOI18N
        JCategoria.add(category);
        category.setBounds(21, 11, 40, 20);

        Izquierda.add(JCategoria);
        JCategoria.setBounds(0, 220, 270, 40);

        JCarrito.setBackground(new java.awt.Color(85, 65, 118));
        JCarrito.setPreferredSize(new java.awt.Dimension(270, 40));
        JCarrito.setLayout(null);

        comprasl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comprasl.setForeground(new java.awt.Color(204, 204, 204));
        comprasl.setText("Compras");
        JCarrito.add(comprasl);
        comprasl.setBounds(90, 10, 150, 20);

        buy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Compras25.png"))); // NOI18N
        JCarrito.add(buy);
        buy.setBounds(20, 0, 32, 40);

        Izquierda.add(JCarrito);
        JCarrito.setBounds(0, 260, 270, 40);

        JAyuda.setBackground(new java.awt.Color(85, 65, 118));
        JAyuda.setPreferredSize(new java.awt.Dimension(270, 40));
        JAyuda.setLayout(null);

        ayudal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ayudal.setForeground(new java.awt.Color(204, 204, 204));
        ayudal.setText("Ayuda/PQR");
        JAyuda.add(ayudal);
        ayudal.setBounds(90, 10, 150, 20);

        safe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/25.png"))); // NOI18N
        JAyuda.add(safe);
        safe.setBounds(20, 0, 32, 40);

        Izquierda.add(JAyuda);
        JAyuda.setBounds(0, 300, 270, 40);

        JAcerca.setBackground(new java.awt.Color(85, 65, 118));
        JAcerca.setPreferredSize(new java.awt.Dimension(270, 40));
        JAcerca.setLayout(null);

        acercaL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        acercaL.setForeground(new java.awt.Color(204, 204, 204));
        acercaL.setText("Acerca de ");
        JAcerca.add(acercaL);
        acercaL.setBounds(90, 10, 150, 20);
        JAcerca.add(jLabel7);
        jLabel7.setBounds(20, 10, 32, 0);

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Acerca25.png"))); // NOI18N
        JAcerca.add(help);
        help.setBounds(20, 0, 32, 30);

        Izquierda.add(JAcerca);
        JAcerca.setBounds(0, 340, 270, 40);

        getContentPane().add(Izquierda);
        Izquierda.setBounds(0, 0, 270, 630);

        JHeader.setBackground(new java.awt.Color(100, 25, 115));
        JHeader.setLayout(null);

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/minimize.png"))); // NOI18N
        JHeader.add(minimize);
        minimize.setBounds(670, 10, 20, 20);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close20.png"))); // NOI18N
        JHeader.add(close);
        close.setBounds(700, 10, 20, 20);

        titleHeader.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleHeader.setForeground(new java.awt.Color(204, 204, 204));
        titleHeader.setText("Categoria");
        JHeader.add(titleHeader);
        titleHeader.setBounds(100, 30, 230, 50);

        iconHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CategoryHeader.png"))); // NOI18N
        JHeader.add(iconHeader);
        iconHeader.setBounds(30, 30, 90, 50);

        getContentPane().add(JHeader);
        JHeader.setBounds(270, 0, 730, 120);

        JBody.setBackground(new java.awt.Color(235, 235, 235));
        JBody.setLayout(null);

        JClig.setBackground(new java.awt.Color(255, 255, 255));
        JClig.setLayout(null);

        Glig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bloqueadro.png"))); // NOI18N
        Glig.setText("jLabel1");
        JClig.add(Glig);
        Glig.setBounds(30, 10, 120, 150);

        JBody.add(JClig);
        JClig.setBounds(60, 20, 190, 170);

        JTricovi.setBackground(new java.awt.Color(255, 255, 255));
        JTricovi.setLayout(null);

        Tricovit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trivol.PNG"))); // NOI18N
        JTricovi.add(Tricovit);
        Tricovit.setBounds(-10, 10, 210, 200);

        JBody.add(JTricovi);
        JTricovi.setBounds(530, 20, 190, 170);

        JDolexNi.setBackground(new java.awt.Color(255, 255, 255));
        JDolexNi.setLayout(null);

        Dolexni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DolexNiño.PNG"))); // NOI18N
        JDolexNi.add(Dolexni);
        Dolexni.setBounds(20, 10, 120, 120);

        JBody.add(JDolexNi);
        JDolexNi.setBounds(300, 280, 190, 160);

        JDolfenox.setBackground(new java.awt.Color(255, 255, 255));
        JDolfenox.setLayout(null);

        Dolfenox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dolfe.PNG"))); // NOI18N
        JDolfenox.add(Dolfenox);
        Dolfenox.setBounds(20, 10, 160, 120);

        JBody.add(JDolfenox);
        JDolfenox.setBounds(60, 280, 190, 160);

        JDolex.setBackground(new java.awt.Color(255, 255, 255));
        JDolex.setLayout(null);

        Dolex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dolex.png"))); // NOI18N
        JDolex.add(Dolex);
        Dolex.setBounds(20, 30, 160, 130);

        JBody.add(JDolex);
        JDolex.setBounds(300, 20, 190, 170);

        JVoltaren.setBackground(new java.awt.Color(255, 255, 255));
        JVoltaren.setLayout(null);

        voltaren.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/asad.png"))); // NOI18N
        JVoltaren.add(voltaren);
        voltaren.setBounds(0, 30, 180, 100);

        JBody.add(JVoltaren);
        JVoltaren.setBounds(530, 280, 190, 160);

        priceDolfenox.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        priceDolfenox.setText("$ 30.650");
        JBody.add(priceDolfenox);
        priceDolfenox.setBounds(60, 450, 100, 40);

        priceGli.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        priceGli.setText("$ 81.050");
        JBody.add(priceGli);
        priceGli.setBounds(50, 210, 100, 40);

        PriceDolex.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PriceDolex.setText("$ 48.100");
        JBody.add(PriceDolex);
        PriceDolex.setBounds(300, 210, 100, 40);

        priceTricovi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        priceTricovi.setText("$ 173.900");
        JBody.add(priceTricovi);
        priceTricovi.setBounds(530, 210, 110, 40);

        PriceVoltaren.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PriceVoltaren.setText("$ 68.300");
        JBody.add(PriceVoltaren);
        PriceVoltaren.setBounds(530, 450, 100, 40);

        priceDolexNi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        priceDolexNi.setText("$ 19.200");
        JBody.add(priceDolexNi);
        priceDolexNi.setBounds(300, 450, 100, 40);

        buttonDolfenox.setBackground(new java.awt.Color(100, 25, 115));
        buttonDolfenox.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        buttonDolfenox.setForeground(new java.awt.Color(204, 204, 204));
        buttonDolfenox.setText("Add");
        buttonDolfenox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDolfenox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDolfenoxActionPerformed(evt);
            }
        });
        JBody.add(buttonDolfenox);
        buttonDolfenox.setBounds(190, 460, 60, 23);

        buttonGlic.setBackground(new java.awt.Color(100, 25, 115));
        buttonGlic.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        buttonGlic.setForeground(new java.awt.Color(204, 204, 204));
        buttonGlic.setText("Add");
        buttonGlic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonGlic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGlicActionPerformed(evt);
            }
        });
        JBody.add(buttonGlic);
        buttonGlic.setBounds(180, 220, 60, 23);

        butonDolex.setBackground(new java.awt.Color(100, 25, 115));
        butonDolex.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        butonDolex.setForeground(new java.awt.Color(204, 204, 204));
        butonDolex.setText("Add");
        butonDolex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butonDolex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonDolexActionPerformed(evt);
            }
        });
        JBody.add(butonDolex);
        butonDolex.setBounds(430, 220, 60, 23);

        buttonTricovit.setBackground(new java.awt.Color(100, 25, 115));
        buttonTricovit.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        buttonTricovit.setForeground(new java.awt.Color(204, 204, 204));
        buttonTricovit.setText("Add");
        buttonTricovit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTricovit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTricovitActionPerformed(evt);
            }
        });
        JBody.add(buttonTricovit);
        buttonTricovit.setBounds(650, 220, 60, 23);

        buttonVoltaren.setBackground(new java.awt.Color(100, 25, 115));
        buttonVoltaren.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        buttonVoltaren.setForeground(new java.awt.Color(204, 204, 204));
        buttonVoltaren.setText("Add");
        buttonVoltaren.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonVoltaren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVoltarenActionPerformed(evt);
            }
        });
        JBody.add(buttonVoltaren);
        buttonVoltaren.setBounds(660, 460, 60, 23);

        buttonDolexNi.setBackground(new java.awt.Color(100, 25, 115));
        buttonDolexNi.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        buttonDolexNi.setForeground(new java.awt.Color(204, 204, 204));
        buttonDolexNi.setText("Add");
        buttonDolexNi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDolexNi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDolexNiActionPerformed(evt);
            }
        });
        JBody.add(buttonDolexNi);
        buttonDolexNi.setBounds(430, 460, 60, 23);

        getContentPane().add(JBody);
        JBody.setBounds(270, 120, 730, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoryClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryClick
        
    }//GEN-LAST:event_CategoryClick

    private void JCategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JCategoriaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_JCategoriaMouseEntered

    private void buttonDolfenoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDolfenoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDolfenoxActionPerformed

    private void buttonGlicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGlicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGlicActionPerformed

    private void butonDolexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonDolexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butonDolexActionPerformed

    private void buttonTricovitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTricovitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTricovitActionPerformed

    private void buttonVoltarenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVoltarenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVoltarenActionPerformed

    private void buttonDolexNiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDolexNiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDolexNiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pruebas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pruebas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pruebas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pruebas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pruebas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dolex;
    private javax.swing.JLabel Dolexni;
    private javax.swing.JLabel Dolfenox;
    private javax.swing.JLabel Glig;
    private javax.swing.JPanel Izquierda;
    private javax.swing.JPanel JAcerca;
    private javax.swing.JPanel JAyuda;
    private javax.swing.JPanel JBody;
    private javax.swing.JPanel JCarrito;
    private javax.swing.JPanel JCategoria;
    private javax.swing.JPanel JClig;
    private javax.swing.JPanel JDolex;
    private javax.swing.JPanel JDolexNi;
    private javax.swing.JPanel JDolfenox;
    private javax.swing.JPanel JHeader;
    private javax.swing.JPanel JTricovi;
    private javax.swing.JPanel JVoltaren;
    private javax.swing.JLabel PriceDolex;
    private javax.swing.JLabel PriceVoltaren;
    private javax.swing.JLabel Tricovit;
    private javax.swing.JLabel acercaL;
    private javax.swing.JLabel ayudal;
    private javax.swing.JButton butonDolex;
    private javax.swing.JButton buttonDolexNi;
    private javax.swing.JButton buttonDolfenox;
    private javax.swing.JButton buttonGlic;
    private javax.swing.JButton buttonTricovit;
    private javax.swing.JButton buttonVoltaren;
    private javax.swing.JLabel buy;
    private javax.swing.JLabel categoriasl;
    private javax.swing.JLabel category;
    private javax.swing.JLabel close;
    private javax.swing.JLabel comprasl;
    private javax.swing.JLabel help;
    private javax.swing.JLabel iconHeader;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel priceDolexNi;
    private javax.swing.JLabel priceDolfenox;
    private javax.swing.JLabel priceGli;
    private javax.swing.JLabel priceTricovi;
    private javax.swing.JLabel safe;
    private javax.swing.JLabel titleHeader;
    private javax.swing.JLabel voltaren;
    // End of variables declaration//GEN-END:variables
}
